### ISSUE TITLE
Error in reading goals Maven Artifact 

### ISSUE THREAD

**Issue by KeerthiRamalingappa** [KeerthiRamalingappa/SparkJavaTraining#1]
[INFO] Scanning for projects...
[WARNING] Failed to canonicalize path C:\Users\Keerthi\.m2\repository\<org\apache\maven\plugins>\<maven-compiler-plugin>[\<3.1>]\<maven-compiler-plugin>[-<3.1>].pom.lastUpdated: The filename, directory name, or volume label syntax is incorrect
[INFO] Downloading: https://repo.maven.apache.org/maven2/<org/apache/maven/plugins>/<maven-compiler-plugin>[/<3.1>]/<maven-compiler-plugin>[-<3.1>].pom
[WARNING] Failed to canonicalize path C:\Users\Keerthi\.m2\repository\<org\apache\maven\plugins>\<maven-compiler-plugin>[\<3.1>]\<maven-compiler-plugin>[-<3.1>].pom.lastUpdated: The filename, directory name, or volume label syntax is incorrect
[WARNING] Failed to create parent directories for tracking file C:\Users\Keerthi\.m2\repository\<org\apache\maven\plugins>\<maven-compiler-plugin>[\<3.1>]\<maven-compiler-plugin>[-<3.1>].pom.lastUpdated
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.521 s
[INFO] Finished at: 2018-02-12T12:57:58-06:00
[INFO] Final Memory: 6M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin <org.apache.maven.plugins>:<maven-compiler-plugin>[:<3.1>] or one of its dependencies could not be resolved: Failed to read artifact descriptor for <org.apache.maven.plugins>:<maven-compiler-plugin>[:jar:<3.1>]: Could not transfer artifact <org.apache.maven.plugins>:<maven-compiler-plugin>[:pom:<3.1>] from/to central (https://repo.maven.apache.org/maven2): NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by kunallahiri** [comment]
You are trying to download a plugin project as a dependency. Remove the dependency of maven compiler from your pom.xml. Add the version in the plugins section:
`13             <plugin> 
14                 <groupId>org.apache.maven.plugins</groupId> 
15                 <artifactId>maven-compiler-plugin</artifactId> 
16                  
17                 <configuration> 
18                     <source>1.7</source> 
19                     <target>1.7</target> 
20                 </configuration> 
21             </plugin> 
`

**Comment by kunallahiri** [comment]
Any luck after removing the dependency of maven-compiler and adding version to the plugin.

**Comment by kunallahiri** [comment]
close it if it has been resolved.
